# Credit to author Ulises Martinez
# Source: https://mxulises.medium.com/simple-prometheus-setup-on-docker-compose-f702d5f98579

global:
  scrape_interval: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: coffee-shop-app
    static_configs:
      - targets:
          - "api:3333"
